cytomining/DeepProfiler

- dataset/__main__.py
- dataset/indexing.py
- dataset/metadata.py
Tools for dataset preparation ready. All four operations are integrated and parameterized.
> Factorized and parameterized script 01 for metadata

- dataset/image_dataset.py
- dataset/metadata.py
- dataset/pixels.py
- learning/__main__.py
- learning/cropping.py
- learning/models.py
- learning/training.py
- learning/validation.py
Ready to integrate functionalities and make keras-resnet the main model provider for this version.
> Keras resnet

- dataset/image_dataset.py
- learning/models.py
The original VGG-like code was added in this version. Integrating even though we no longer use this model.
> First model for treatment classification

- AUTHORS.md
> Resolving Issue #39

- tests/dataset/test_pixels.py
creating tests for dataset/pixels
> Resolving Issue #34

- deepprofiler/dataset/utils.py
- tests/dataset/test_utils.py
creating tests for dataset/utils and making corresponding changes to code
@jccaicedo
> Resolving Issue #35

- deepprofiler/dataset/indexing.py
- deepprofiler/dataset/utils.py
- tests/dataset/test_indexing.py
- tests/dataset/test_utils.py
creating tests for dataset/indexing and making corresponding changes to code
@jccaicedo
> Resolving Issue #33

- deepprofiler/examples/config/test_boxes.json
- deepprofiler/imaging/boxes.py
- tests/dataset/test_indexing.py
- tests/imaging/test_boxes.py
adding tests for imaging/boxes
> Resolving Issue #58

- README.md
> Resolving Issue #81

- codecov.yml
> resolving issue #84

- README.md
> resolving issue #78

- README.md
Hey,
This looks really awesome! I added a comet.ml badge.
Right now it leads to the main homepage but if you have a public project with experiments you can point it there. This way people can review experiments and results.
> Adding comet.ml badge

- deepprofiler/learning/model.py
- deepprofiler/learning/profiling.py
- plugins/models/autoencoder.py
- plugins/models/avb.py
- plugins/models/cnn.py
- plugins/models/gan.py
- plugins/models/resnet18.py
- plugins/models/vae.py
- tests/deepprofiler/learning/test_model.py
- tests/deepprofiler/learning/test_profiling.py
- tests/deepprofiler/learning/test_training.py
- tests/plugins/models/test_autoencoder.py
- tests/plugins/models/test_cnn.py
- tests/plugins/models/test_gan.py
- tests/plugins/models/test_resnet18.py
- tests/plugins/models/test_vae.py
Only 1 minor change to profiling was necessary
> Implement GAN model

- deepprofiler/__main__.py
- deepprofiler/imaging/cropping.py
- deepprofiler/learning/model.py
- deepprofiler/learning/profiling.py
- deepprofiler/learning/validation.py
- plugins/models/cnn.py
- plugins/models/inception_resnet_v2.py
- tests/deepprofiler/learning/test_model.py
- tests/deepprofiler/learning/test_profiling.py
- tests/files/config/test.json
- tests/plugins/models/test_gan.py
Removed manual tf variable initialization that was causing problem with saving/loading weights, fixed compression not working, fixed problem with cnn, added experiment name option, added message when image has no crops to profile
> Critical fixes

- deepprofiler/dataset/compression.py
- tests/files/config/test.json
You also need to change the field name in the example data config.
> Replace config field name "control_value" with "control_id"

- deepprofiler/learning/model.py
- This line should be commented. Currently, "start from epoch x" feature is not working as it is being overwritten by this random initialization.
> Incorrect duplicate random initialization.

- deepprofiler/dataset/compression.py
- deepprofiler/dataset/illumination_statistics.py
- deepprofiler/dataset/image_dataset.py
- deepprofiler/dataset/indexing.py
- deepprofiler/imaging/cropping.py
- deepprofiler/learning/profiling.py
- plugins/crop_generators/repeat_channel_crop_generator.py
- plugins/models/autoencoder.py
- plugins/models/cnn.py
- plugins/models/densenet.py
- plugins/models/gan.py
- plugins/models/inception_resnet_v2.py
- plugins/models/resnet101.py
- plugins/models/resnet152.py
- plugins/models/resnet18.py
- plugins/models/resnet200.py
- plugins/models/resnet50.py
- plugins/models/vae.py
- tests/deepprofiler/dataset/test_image_dataset.py
- tests/deepprofiler/imaging/test_cropping.py
- tests/deepprofiler/learning/test_profiling.py
- tests/files/config/test.json
- tests/plugins/crop_generators/test_mixup_crop_generator.py
- tests/plugins/models/test_gan.py
Config from example data needs to be updated
> Split config field "prepare" into "prepare" and "dataset"

- deepprofiler/dataset/compression.py
- plugins/models/densenet.py
- tests/files/config/test.json
Get rid of label_composition and control_field config fields.
> Get rid of label_composition and control_field config fields.

- deepprofiler/imaging/augmentations.py
- deepprofiler/imaging/cropping.py
- deepprofiler/learning/model.py
- deepprofiler/learning/profiling.py
- plugins/crop_generators/repeat_channel_crop_generator.py
- plugins/models/densenet.py
- plugins/models/gan.py
- plugins/models/inception_resnet_v2.py
- setup.py
- tests/deepprofiler/imaging/test_augmentations.py
- tests/deepprofiler/imaging/test_cropping.py
- tests/deepprofiler/learning/test_profiling.py
- tests/deepprofiler/learning/test_validation.py
- tests/plugins/crop_generators/test_autoencoder_crop_generator.py
- tests/plugins/crop_generators/test_mixup_crop_generator.py
- tests/plugins/metrics/test_top_k.py
Modified tf imports to import tf2 but run only tf1. Added tf 2.1.*  to requirements and specified python requirement as <3.8
> Changed tensorflow imports and tensorflow + python requirements

- deepprofiler/imaging/augmentations.py
- deepprofiler/imaging/cropping.py
- deepprofiler/learning/model.py
- deepprofiler/learning/profiling.py
- plugins/crop_generators/repeat_channel_crop_generator.py
- plugins/models/densenet.py
- plugins/models/gan.py
- plugins/models/inception_resnet_v2.py
- setup.py
- tests/deepprofiler/imaging/test_augmentations.py
- tests/deepprofiler/imaging/test_cropping.py
- tests/deepprofiler/learning/test_profiling.py
- tests/deepprofiler/learning/test_validation.py
- tests/plugins/crop_generators/test_autoencoder_crop_generator.py
- tests/plugins/crop_generators/test_mixup_crop_generator.py
- tests/plugins/metrics/test_top_k.py
Reverts cytomining/DeepProfiler#193
> Revert "Changed tensorflow imports and tensorflow + python requirements"

- README.md
> Added flags to commands in readme

- deepprofiler/dataset/compression.py
- deepprofiler/dataset/illumination_statistics.py
I had shape error, so I also changed to `self.controls_distribution[c] += numpy.histogram(image, bins=256)[0]` as default number of bins is 10.
> Fix prepare.

- tests/deepprofiler/learning/test_profiling.py
The bug was caused by this https://github.com/tensorflow/tensorflow/issues/26472
> https://github.com/cytomining/DeepProfiler/issues/211

- setup.py
- tests/deepprofiler/learning/test_profiling.py
> Fix profiling tests and setup.py keras version.

- deepprofiler/__main__.py
- deepprofiler/dataset/image_dataset.py
- deepprofiler/imaging/cropping.py
- plugins/crop_generators/mixup_crop_generator.py
- tests/files/config/test.json
I did not rename `training_queues` and `queue_threads` on purpose as I think queues are built from cache.
> Change config parameter queue to cache

- deepprofiler/imaging/cropping.py
- deepprofiler/learning/profiling.py
- deepprofiler/learning/validation.py
- tests/deepprofiler/imaging/test_cropping.py
- tests/plugins/crop_generators/test_autoencoder_crop_generator.py
Features computed by DeepProfiler are stored in numpy arrays using the `.npz` format. In addition to the features, we have included metadata to facilitate downstream analysis. Here is the proposed structure:
```
{
"features": array,
"metadata": dict({
"Metadata_Pate": value,
"Metadata_Well": value,
"Metadata_Site": value,
"Metadata_Model": value,
"other_keys": other_values ...
}),
"locations": array
}
```
Features are stored in directories named after the plates. Feature files are named after the well and site. The `.npz` files contain a feature vector (`features`), metadata (`metadata`) and the x,y coordinates of single cells (`locations`). This will be the format supported by DeepProfiler for generating and distributing features computed on different datasets.
**Note**: In order to read …
> Issue 229 - Format of feature files

- deepprofiler/__main__.py
Make a directory for compressed metadata https://github.com/cytomining/DeepProfiler/issues/242
> Make directory for compressed metadata

- plugins/models/efficientnet.py
- plugins/models/resnet.py
Hi Juan, could you have a look at the code and provide feedback? 
I checked this code on a very small portion of TA-ORF (~10 images) and it worked fine. 
If everything is fine with the code, please don't merge it just yet.
I am going to run tests for the whole TA-ORF dataset and get back here with the results.
> ResNet pretrained, Efficient training

- plugins/models/autoencoder.py
- plugins/models/densenet.py
- plugins/models/inception_resnet_v2.py
- tests/deepprofiler/learning/test_model.py
- tests/deepprofiler/learning/test_profiling.py
- tests/plugins/models/test_autoencoder.py
- tests/plugins/models/test_cnn.py
- tests/plugins/models/test_densenet.py
- tests/plugins/models/test_efficientnet.py
- tests/plugins/models/test_resnet.py
Hi, this PR fixes https://github.com/cytomining/DeepProfiler/issues/246 + restores DenseNet (not tested, just restored the code) + fix of some tests with a relative issue as in IncResV2.
> Fix IncResV2 + fix some tests + restore DenseNet

- deepprofiler/learning/model.py
> Init tf variables

- deepprofiler/learning/profiling.py
- setup.py
Missing dependencies when installing in a brand-new environment.
> Add tqdm and tensorflow as dependencies

- deepprofiler/dataset/image_dataset.py
- deepprofiler/learning/model.py
- plugins/crop_generators/online_labels_cropgen.py
- plugins/crop_generators/sampled_crop_generator.py
- plugins/models/efficientnet.py
Closes the issue https://github.com/cytomining/DeepProfiler/issues/283 .
We need to revisit for ResNet.
> Fix sampled crop generator and EfficientNet

- deepprofiler/learning/tf2train.py
- plugins/crop_generators/sampled_crop_generator.py
Now TF2 training uses `sample_crop_generator`.
It means that `sample_crop_generator` does not work with TF1 training anymore.
> Sampled crop generator to TFv2

- deepprofiler/dataset/sampling.py
Is supposed to solve #331.
I have checked it on test dataset of a few images, while one of them was empty but with locations. 
In old version we would get entries of empty images in the metadata, now those entries are filtered.
> Add filter for empty images.

- deepprofiler/__main__.py
Enforce CPU for the single-cell export.
Supposed to close #338.
> Enforce CPU for single-cell export.

- plugins/crop_generators/full_image_crop_generator.py
> Replace tiff\tif to png if compression is on.
